# Use the .NET SDK as the build environment
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY News.Api/*.csproj ./News.Api/
COPY News.Application/*.csproj ./News.Application/
COPY News.Persistence/*.csproj ./News.Persistence/
COPY News.Domain/*.csproj ./News.Domain/
RUN dotnet restore

# Copy everything else and build
COPY News.Api/. ./News.Api/
COPY News.Application/. ./News.Application/
COPY News.Persistence/. ./News.Persistence/
COPY News.Domain/. ./News.Domain/
WORKDIR /app/News.Api
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/News.Api/out .
ENTRYPOINT ["dotnet", "News.Api.dll"]
